/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R260519RouteImport } from './routes/260519'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactusRouteImport } from './routes/contactus'
import { Route as HomeRouteImport } from './routes/home'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RefundAndCancellationRouteImport } from './routes/refund-and-cancellation'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as VerifyCodeRouteImport } from './routes/verify-code'
import { Route as R260519IndexRouteImport } from './routes/260519.index'
import { Route as R260519AnalyticsRouteImport } from './routes/260519.analytics'
import { Route as R260519CategoriesRouteImport } from './routes/260519.categories'
import { Route as R260519CouponsRouteImport } from './routes/260519.coupons'
import { Route as R260519CustomersRouteImport } from './routes/260519.customers'
import { Route as R260519OrdersRouteImport } from './routes/260519.orders'
import { Route as R260519ProductsRouteImport } from './routes/260519.products'
import { Route as R260519ReviewsRouteImport } from './routes/260519.reviews'
import { Route as R260519SettingsRouteImport } from './routes/260519.settings'
import { Route as R260519SuppliersRouteImport } from './routes/260519.suppliers'
import { Route as R260519SupportRouteImport } from './routes/260519.support'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as GamesAllRouteImport } from './routes/games.all'
import { Route as GamesPlaystationGamesRouteImport } from './routes/games.playstation-games'
import { Route as GamesSteamGamesRouteImport } from './routes/games.steam-games'
import { Route as GamesSubscriptionsRouteImport } from './routes/games.subscriptions'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as ApiPublicCashfreeWebhookRouteImport } from './routes/api/public/cashfree-webhook'
import { Route as ApiPublicCfSdkRouteImport } from './routes/api/public/cf-sdk'
import { Route as ApiPublicOxapayWebhookRouteImport } from './routes/api/public/oxapay-webhook'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicProductImageSplatRouteImport } from './routes/api/public/product-image.$'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R260519Route = R260519RouteImport.update({
  id: '/260519',
  path: '/260519',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactusRoute = ContactusRouteImport.update({
  id: '/contactus',
  path: '/contactus',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundAndCancellationRoute = RefundAndCancellationRouteImport.update({
  id: '/refund-and-cancellation',
  path: '/refund-and-cancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify-code',
  path: '/verify-code',
  getParentRoute: () => rootRouteImport,
} as any)
const R260519IndexRoute = R260519IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => R260519Route,
} as any)
const R260519AnalyticsRoute = R260519AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => R260519Route,
} as any)
const R260519CategoriesRoute = R260519CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => R260519Route,
} as any)
const R260519CouponsRoute = R260519CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => R260519Route,
} as any)
const R260519CustomersRoute = R260519CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => R260519Route,
} as any)
const R260519OrdersRoute = R260519OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => R260519Route,
} as any)
const R260519ProductsRoute = R260519ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => R260519Route,
} as any)
const R260519ReviewsRoute = R260519ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => R260519Route,
} as any)
const R260519SettingsRoute = R260519SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => R260519Route,
} as any)
const R260519SuppliersRoute = R260519SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => R260519Route,
} as any)
const R260519SupportRoute = R260519SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => R260519Route,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesAllRoute = GamesAllRouteImport.update({
  id: '/games/all',
  path: '/games/all',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesPlaystationGamesRoute = GamesPlaystationGamesRouteImport.update({
  id: '/games/playstation-games',
  path: '/games/playstation-games',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSteamGamesRoute = GamesSteamGamesRouteImport.update({
  id: '/games/steam-games',
  path: '/games/steam-games',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSubscriptionsRoute = GamesSubscriptionsRouteImport.update({
  id: '/games/subscriptions',
  path: '/games/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCashfreeWebhookRoute =
  ApiPublicCashfreeWebhookRouteImport.update({
    id: '/api/public/cashfree-webhook',
    path: '/api/public/cashfree-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCfSdkRoute = ApiPublicCfSdkRouteImport.update({
  id: '/api/public/cf-sdk',
  path: '/api/public/cf-sdk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOxapayWebhookRoute = ApiPublicOxapayWebhookRouteImport.update({
  id: '/api/public/oxapay-webhook',
  path: '/api/public/oxapay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductImageSplatRoute =
  ApiPublicProductImageSplatRouteImport.update({
    id: '/api/public/product-image/$',
    path: '/api/public/product-image/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/260519': typeof R260519RouteWithChildren
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/contactus': typeof ContactusRoute
  '/home': typeof HomeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-and-cancellation': typeof RefundAndCancellationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/verify-code': typeof VerifyCodeRoute
  '/260519/analytics': typeof R260519AnalyticsRoute
  '/260519/categories': typeof R260519CategoriesRoute
  '/260519/coupons': typeof R260519CouponsRoute
  '/260519/customers': typeof R260519CustomersRoute
  '/260519/orders': typeof R260519OrdersRoute
  '/260519/products': typeof R260519ProductsRoute
  '/260519/reviews': typeof R260519ReviewsRoute
  '/260519/settings': typeof R260519SettingsRoute
  '/260519/suppliers': typeof R260519SuppliersRoute
  '/260519/support': typeof R260519SupportRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/games/all': typeof GamesAllRoute
  '/games/playstation-games': typeof GamesPlaystationGamesRoute
  '/games/steam-games': typeof GamesSteamGamesRoute
  '/games/subscriptions': typeof GamesSubscriptionsRoute
  '/order/$id': typeof OrderIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/260519/': typeof R260519IndexRoute
  '/games/': typeof GamesIndexRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/api/public/cf-sdk': typeof ApiPublicCfSdkRoute
  '/api/public/oxapay-webhook': typeof ApiPublicOxapayWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/product-image/$': typeof ApiPublicProductImageSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/contactus': typeof ContactusRoute
  '/home': typeof HomeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-and-cancellation': typeof RefundAndCancellationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/verify-code': typeof VerifyCodeRoute
  '/260519/analytics': typeof R260519AnalyticsRoute
  '/260519/categories': typeof R260519CategoriesRoute
  '/260519/coupons': typeof R260519CouponsRoute
  '/260519/customers': typeof R260519CustomersRoute
  '/260519/orders': typeof R260519OrdersRoute
  '/260519/products': typeof R260519ProductsRoute
  '/260519/reviews': typeof R260519ReviewsRoute
  '/260519/settings': typeof R260519SettingsRoute
  '/260519/suppliers': typeof R260519SuppliersRoute
  '/260519/support': typeof R260519SupportRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/games/all': typeof GamesAllRoute
  '/games/playstation-games': typeof GamesPlaystationGamesRoute
  '/games/steam-games': typeof GamesSteamGamesRoute
  '/games/subscriptions': typeof GamesSubscriptionsRoute
  '/order/$id': typeof OrderIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/260519': typeof R260519IndexRoute
  '/games': typeof GamesIndexRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/api/public/cf-sdk': typeof ApiPublicCfSdkRoute
  '/api/public/oxapay-webhook': typeof ApiPublicOxapayWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/product-image/$': typeof ApiPublicProductImageSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/260519': typeof R260519RouteWithChildren
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/contactus': typeof ContactusRoute
  '/home': typeof HomeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-and-cancellation': typeof RefundAndCancellationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/verify-code': typeof VerifyCodeRoute
  '/260519/analytics': typeof R260519AnalyticsRoute
  '/260519/categories': typeof R260519CategoriesRoute
  '/260519/coupons': typeof R260519CouponsRoute
  '/260519/customers': typeof R260519CustomersRoute
  '/260519/orders': typeof R260519OrdersRoute
  '/260519/products': typeof R260519ProductsRoute
  '/260519/reviews': typeof R260519ReviewsRoute
  '/260519/settings': typeof R260519SettingsRoute
  '/260519/suppliers': typeof R260519SuppliersRoute
  '/260519/support': typeof R260519SupportRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/games/all': typeof GamesAllRoute
  '/games/playstation-games': typeof GamesPlaystationGamesRoute
  '/games/steam-games': typeof GamesSteamGamesRoute
  '/games/subscriptions': typeof GamesSubscriptionsRoute
  '/order/$id': typeof OrderIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/260519/': typeof R260519IndexRoute
  '/games/': typeof GamesIndexRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/api/public/cf-sdk': typeof ApiPublicCfSdkRoute
  '/api/public/oxapay-webhook': typeof ApiPublicOxapayWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/product-image/$': typeof ApiPublicProductImageSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/260519'
    | '/account'
    | '/checkout'
    | '/contactus'
    | '/home'
    | '/privacy-policy'
    | '/refund-and-cancellation'
    | '/reset-password'
    | '/signin'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/verify-code'
    | '/260519/analytics'
    | '/260519/categories'
    | '/260519/coupons'
    | '/260519/customers'
    | '/260519/orders'
    | '/260519/products'
    | '/260519/reviews'
    | '/260519/settings'
    | '/260519/suppliers'
    | '/260519/support'
    | '/email/unsubscribe'
    | '/games/all'
    | '/games/playstation-games'
    | '/games/steam-games'
    | '/games/subscriptions'
    | '/order/$id'
    | '/products/$id'
    | '/260519/'
    | '/games/'
    | '/api/public/cashfree-webhook'
    | '/api/public/cf-sdk'
    | '/api/public/oxapay-webhook'
    | '/lovable/email/suppression'
    | '/api/public/product-image/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/checkout'
    | '/contactus'
    | '/home'
    | '/privacy-policy'
    | '/refund-and-cancellation'
    | '/reset-password'
    | '/signin'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/verify-code'
    | '/260519/analytics'
    | '/260519/categories'
    | '/260519/coupons'
    | '/260519/customers'
    | '/260519/orders'
    | '/260519/products'
    | '/260519/reviews'
    | '/260519/settings'
    | '/260519/suppliers'
    | '/260519/support'
    | '/email/unsubscribe'
    | '/games/all'
    | '/games/playstation-games'
    | '/games/steam-games'
    | '/games/subscriptions'
    | '/order/$id'
    | '/products/$id'
    | '/260519'
    | '/games'
    | '/api/public/cashfree-webhook'
    | '/api/public/cf-sdk'
    | '/api/public/oxapay-webhook'
    | '/lovable/email/suppression'
    | '/api/public/product-image/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/260519'
    | '/account'
    | '/checkout'
    | '/contactus'
    | '/home'
    | '/privacy-policy'
    | '/refund-and-cancellation'
    | '/reset-password'
    | '/signin'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/verify-code'
    | '/260519/analytics'
    | '/260519/categories'
    | '/260519/coupons'
    | '/260519/customers'
    | '/260519/orders'
    | '/260519/products'
    | '/260519/reviews'
    | '/260519/settings'
    | '/260519/suppliers'
    | '/260519/support'
    | '/email/unsubscribe'
    | '/games/all'
    | '/games/playstation-games'
    | '/games/steam-games'
    | '/games/subscriptions'
    | '/order/$id'
    | '/products/$id'
    | '/260519/'
    | '/games/'
    | '/api/public/cashfree-webhook'
    | '/api/public/cf-sdk'
    | '/api/public/oxapay-webhook'
    | '/lovable/email/suppression'
    | '/api/public/product-image/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R260519Route: typeof R260519RouteWithChildren
  AccountRoute: typeof AccountRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactusRoute: typeof ContactusRoute
  HomeRoute: typeof HomeRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundAndCancellationRoute: typeof RefundAndCancellationRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  GamesAllRoute: typeof GamesAllRoute
  GamesPlaystationGamesRoute: typeof GamesPlaystationGamesRoute
  GamesSteamGamesRoute: typeof GamesSteamGamesRoute
  GamesSubscriptionsRoute: typeof GamesSubscriptionsRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductsIdRoute: typeof ProductsIdRoute
  GamesIndexRoute: typeof GamesIndexRoute
  ApiPublicCashfreeWebhookRoute: typeof ApiPublicCashfreeWebhookRoute
  ApiPublicCfSdkRoute: typeof ApiPublicCfSdkRoute
  ApiPublicOxapayWebhookRoute: typeof ApiPublicOxapayWebhookRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicProductImageSplatRoute: typeof ApiPublicProductImageSplatRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/260519': {
      id: '/260519'
      path: '/260519'
      fullPath: '/260519'
      preLoaderRoute: typeof R260519RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactus': {
      id: '/contactus'
      path: '/contactus'
      fullPath: '/contactus'
      preLoaderRoute: typeof ContactusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-and-cancellation': {
      id: '/refund-and-cancellation'
      path: '/refund-and-cancellation'
      fullPath: '/refund-and-cancellation'
      preLoaderRoute: typeof RefundAndCancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-code': {
      id: '/verify-code'
      path: '/verify-code'
      fullPath: '/verify-code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/260519/': {
      id: '/260519/'
      path: '/'
      fullPath: '/260519/'
      preLoaderRoute: typeof R260519IndexRouteImport
      parentRoute: typeof R260519Route
    }
    '/260519/analytics': {
      id: '/260519/analytics'
      path: '/analytics'
      fullPath: '/260519/analytics'
      preLoaderRoute: typeof R260519AnalyticsRouteImport
      parentRoute: typeof R260519Route
    }
    '/260519/categories': {
      id: '/260519/categories'
      path: '/categories'
      fullPath: '/260519/categories'
      preLoaderRoute: typeof R260519CategoriesRouteImport
      parentRoute: typeof R260519Route
    }
    '/260519/coupons': {
      id: '/260519/coupons'
      path: '/coupons'
      fullPath: '/260519/coupons'
      preLoaderRoute: typeof R260519CouponsRouteImport
      parentRoute: typeof R260519Route
    }
    '/260519/customers': {
      id: '/260519/customers'
      path: '/customers'
      fullPath: '/260519/customers'
      preLoaderRoute: typeof R260519CustomersRouteImport
      parentRoute: typeof R260519Route
    }
    '/260519/orders': {
      id: '/260519/orders'
      path: '/orders'
      fullPath: '/260519/orders'
      preLoaderRoute: typeof R260519OrdersRouteImport
      parentRoute: typeof R260519Route
    }
    '/260519/products': {
      id: '/260519/products'
      path: '/products'
      fullPath: '/260519/products'
      preLoaderRoute: typeof R260519ProductsRouteImport
      parentRoute: typeof R260519Route
    }
    '/260519/reviews': {
      id: '/260519/reviews'
      path: '/reviews'
      fullPath: '/260519/reviews'
      preLoaderRoute: typeof R260519ReviewsRouteImport
      parentRoute: typeof R260519Route
    }
    '/260519/settings': {
      id: '/260519/settings'
      path: '/settings'
      fullPath: '/260519/settings'
      preLoaderRoute: typeof R260519SettingsRouteImport
      parentRoute: typeof R260519Route
    }
    '/260519/suppliers': {
      id: '/260519/suppliers'
      path: '/suppliers'
      fullPath: '/260519/suppliers'
      preLoaderRoute: typeof R260519SuppliersRouteImport
      parentRoute: typeof R260519Route
    }
    '/260519/support': {
      id: '/260519/support'
      path: '/support'
      fullPath: '/260519/support'
      preLoaderRoute: typeof R260519SupportRouteImport
      parentRoute: typeof R260519Route
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/all': {
      id: '/games/all'
      path: '/games/all'
      fullPath: '/games/all'
      preLoaderRoute: typeof GamesAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/playstation-games': {
      id: '/games/playstation-games'
      path: '/games/playstation-games'
      fullPath: '/games/playstation-games'
      preLoaderRoute: typeof GamesPlaystationGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/steam-games': {
      id: '/games/steam-games'
      path: '/games/steam-games'
      fullPath: '/games/steam-games'
      preLoaderRoute: typeof GamesSteamGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/subscriptions': {
      id: '/games/subscriptions'
      path: '/games/subscriptions'
      fullPath: '/games/subscriptions'
      preLoaderRoute: typeof GamesSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cashfree-webhook': {
      id: '/api/public/cashfree-webhook'
      path: '/api/public/cashfree-webhook'
      fullPath: '/api/public/cashfree-webhook'
      preLoaderRoute: typeof ApiPublicCashfreeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cf-sdk': {
      id: '/api/public/cf-sdk'
      path: '/api/public/cf-sdk'
      fullPath: '/api/public/cf-sdk'
      preLoaderRoute: typeof ApiPublicCfSdkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oxapay-webhook': {
      id: '/api/public/oxapay-webhook'
      path: '/api/public/oxapay-webhook'
      fullPath: '/api/public/oxapay-webhook'
      preLoaderRoute: typeof ApiPublicOxapayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/product-image/$': {
      id: '/api/public/product-image/$'
      path: '/api/public/product-image/$'
      fullPath: '/api/public/product-image/$'
      preLoaderRoute: typeof ApiPublicProductImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface R260519RouteChildren {
  R260519AnalyticsRoute: typeof R260519AnalyticsRoute
  R260519CategoriesRoute: typeof R260519CategoriesRoute
  R260519CouponsRoute: typeof R260519CouponsRoute
  R260519CustomersRoute: typeof R260519CustomersRoute
  R260519OrdersRoute: typeof R260519OrdersRoute
  R260519ProductsRoute: typeof R260519ProductsRoute
  R260519ReviewsRoute: typeof R260519ReviewsRoute
  R260519SettingsRoute: typeof R260519SettingsRoute
  R260519SuppliersRoute: typeof R260519SuppliersRoute
  R260519SupportRoute: typeof R260519SupportRoute
  R260519IndexRoute: typeof R260519IndexRoute
}

const R260519RouteChildren: R260519RouteChildren = {
  R260519AnalyticsRoute: R260519AnalyticsRoute,
  R260519CategoriesRoute: R260519CategoriesRoute,
  R260519CouponsRoute: R260519CouponsRoute,
  R260519CustomersRoute: R260519CustomersRoute,
  R260519OrdersRoute: R260519OrdersRoute,
  R260519ProductsRoute: R260519ProductsRoute,
  R260519ReviewsRoute: R260519ReviewsRoute,
  R260519SettingsRoute: R260519SettingsRoute,
  R260519SuppliersRoute: R260519SuppliersRoute,
  R260519SupportRoute: R260519SupportRoute,
  R260519IndexRoute: R260519IndexRoute,
}

const R260519RouteWithChildren =
  R260519Route._addFileChildren(R260519RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R260519Route: R260519RouteWithChildren,
  AccountRoute: AccountRoute,
  CheckoutRoute: CheckoutRoute,
  ContactusRoute: ContactusRoute,
  HomeRoute: HomeRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundAndCancellationRoute: RefundAndCancellationRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  GamesAllRoute: GamesAllRoute,
  GamesPlaystationGamesRoute: GamesPlaystationGamesRoute,
  GamesSteamGamesRoute: GamesSteamGamesRoute,
  GamesSubscriptionsRoute: GamesSubscriptionsRoute,
  OrderIdRoute: OrderIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  GamesIndexRoute: GamesIndexRoute,
  ApiPublicCashfreeWebhookRoute: ApiPublicCashfreeWebhookRoute,
  ApiPublicCfSdkRoute: ApiPublicCfSdkRoute,
  ApiPublicOxapayWebhookRoute: ApiPublicOxapayWebhookRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicProductImageSplatRoute: ApiPublicProductImageSplatRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
