/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyCodeRouteImport } from './routes/verify-code'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundAndCancellationRouteImport } from './routes/refund-and-cancellation'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ContactusRouteImport } from './routes/contactus'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as GamesSubscriptionsRouteImport } from './routes/games.subscriptions'
import { Route as GamesSteamGamesRouteImport } from './routes/games.steam-games'
import { Route as GamesPlaystationGamesRouteImport } from './routes/games.playstation-games'
import { Route as GamesAllRouteImport } from './routes/games.all'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicOxapayWebhookRouteImport } from './routes/api/public/oxapay-webhook'
import { Route as ApiPublicCfSdkRouteImport } from './routes/api/public/cf-sdk'
import { Route as ApiPublicCashfreeWebhookRouteImport } from './routes/api/public/cashfree-webhook'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify-code',
  path: '/verify-code',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundAndCancellationRoute = RefundAndCancellationRouteImport.update({
  id: '/refund-and-cancellation',
  path: '/refund-and-cancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactusRoute = ContactusRouteImport.update({
  id: '/contactus',
  path: '/contactus',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSubscriptionsRoute = GamesSubscriptionsRouteImport.update({
  id: '/games/subscriptions',
  path: '/games/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSteamGamesRoute = GamesSteamGamesRouteImport.update({
  id: '/games/steam-games',
  path: '/games/steam-games',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesPlaystationGamesRoute = GamesPlaystationGamesRouteImport.update({
  id: '/games/playstation-games',
  path: '/games/playstation-games',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesAllRoute = GamesAllRouteImport.update({
  id: '/games/all',
  path: '/games/all',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOxapayWebhookRoute = ApiPublicOxapayWebhookRouteImport.update({
  id: '/api/public/oxapay-webhook',
  path: '/api/public/oxapay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCfSdkRoute = ApiPublicCfSdkRouteImport.update({
  id: '/api/public/cf-sdk',
  path: '/api/public/cf-sdk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCashfreeWebhookRoute =
  ApiPublicCashfreeWebhookRouteImport.update({
    id: '/api/public/cashfree-webhook',
    path: '/api/public/cashfree-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contactus': typeof ContactusRoute
  '/home': typeof HomeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-and-cancellation': typeof RefundAndCancellationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/verify-code': typeof VerifyCodeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/games/all': typeof GamesAllRoute
  '/games/playstation-games': typeof GamesPlaystationGamesRoute
  '/games/steam-games': typeof GamesSteamGamesRoute
  '/games/subscriptions': typeof GamesSubscriptionsRoute
  '/order/$id': typeof OrderIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/games/': typeof GamesIndexRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/api/public/cf-sdk': typeof ApiPublicCfSdkRoute
  '/api/public/oxapay-webhook': typeof ApiPublicOxapayWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/contactus': typeof ContactusRoute
  '/home': typeof HomeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-and-cancellation': typeof RefundAndCancellationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/verify-code': typeof VerifyCodeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/games/all': typeof GamesAllRoute
  '/games/playstation-games': typeof GamesPlaystationGamesRoute
  '/games/steam-games': typeof GamesSteamGamesRoute
  '/games/subscriptions': typeof GamesSubscriptionsRoute
  '/order/$id': typeof OrderIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin': typeof AdminIndexRoute
  '/games': typeof GamesIndexRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/api/public/cf-sdk': typeof ApiPublicCfSdkRoute
  '/api/public/oxapay-webhook': typeof ApiPublicOxapayWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contactus': typeof ContactusRoute
  '/home': typeof HomeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-and-cancellation': typeof RefundAndCancellationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/verify-code': typeof VerifyCodeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/games/all': typeof GamesAllRoute
  '/games/playstation-games': typeof GamesPlaystationGamesRoute
  '/games/steam-games': typeof GamesSteamGamesRoute
  '/games/subscriptions': typeof GamesSubscriptionsRoute
  '/order/$id': typeof OrderIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/games/': typeof GamesIndexRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/api/public/cf-sdk': typeof ApiPublicCfSdkRoute
  '/api/public/oxapay-webhook': typeof ApiPublicOxapayWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/contactus'
    | '/home'
    | '/privacy-policy'
    | '/refund-and-cancellation'
    | '/reset-password'
    | '/signin'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/verify-code'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/support'
    | '/email/unsubscribe'
    | '/games/all'
    | '/games/playstation-games'
    | '/games/steam-games'
    | '/games/subscriptions'
    | '/order/$id'
    | '/products/$id'
    | '/admin/'
    | '/games/'
    | '/api/public/cashfree-webhook'
    | '/api/public/cf-sdk'
    | '/api/public/oxapay-webhook'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/checkout'
    | '/contactus'
    | '/home'
    | '/privacy-policy'
    | '/refund-and-cancellation'
    | '/reset-password'
    | '/signin'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/verify-code'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/support'
    | '/email/unsubscribe'
    | '/games/all'
    | '/games/playstation-games'
    | '/games/steam-games'
    | '/games/subscriptions'
    | '/order/$id'
    | '/products/$id'
    | '/admin'
    | '/games'
    | '/api/public/cashfree-webhook'
    | '/api/public/cf-sdk'
    | '/api/public/oxapay-webhook'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/contactus'
    | '/home'
    | '/privacy-policy'
    | '/refund-and-cancellation'
    | '/reset-password'
    | '/signin'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/verify-code'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/support'
    | '/email/unsubscribe'
    | '/games/all'
    | '/games/playstation-games'
    | '/games/steam-games'
    | '/games/subscriptions'
    | '/order/$id'
    | '/products/$id'
    | '/admin/'
    | '/games/'
    | '/api/public/cashfree-webhook'
    | '/api/public/cf-sdk'
    | '/api/public/oxapay-webhook'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ContactusRoute: typeof ContactusRoute
  HomeRoute: typeof HomeRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundAndCancellationRoute: typeof RefundAndCancellationRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  GamesAllRoute: typeof GamesAllRoute
  GamesPlaystationGamesRoute: typeof GamesPlaystationGamesRoute
  GamesSteamGamesRoute: typeof GamesSteamGamesRoute
  GamesSubscriptionsRoute: typeof GamesSubscriptionsRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductsIdRoute: typeof ProductsIdRoute
  GamesIndexRoute: typeof GamesIndexRoute
  ApiPublicCashfreeWebhookRoute: typeof ApiPublicCashfreeWebhookRoute
  ApiPublicCfSdkRoute: typeof ApiPublicCfSdkRoute
  ApiPublicOxapayWebhookRoute: typeof ApiPublicOxapayWebhookRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-code': {
      id: '/verify-code'
      path: '/verify-code'
      fullPath: '/verify-code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-and-cancellation': {
      id: '/refund-and-cancellation'
      path: '/refund-and-cancellation'
      fullPath: '/refund-and-cancellation'
      preLoaderRoute: typeof RefundAndCancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactus': {
      id: '/contactus'
      path: '/contactus'
      fullPath: '/contactus'
      preLoaderRoute: typeof ContactusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/subscriptions': {
      id: '/games/subscriptions'
      path: '/games/subscriptions'
      fullPath: '/games/subscriptions'
      preLoaderRoute: typeof GamesSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/steam-games': {
      id: '/games/steam-games'
      path: '/games/steam-games'
      fullPath: '/games/steam-games'
      preLoaderRoute: typeof GamesSteamGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/playstation-games': {
      id: '/games/playstation-games'
      path: '/games/playstation-games'
      fullPath: '/games/playstation-games'
      preLoaderRoute: typeof GamesPlaystationGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/all': {
      id: '/games/all'
      path: '/games/all'
      fullPath: '/games/all'
      preLoaderRoute: typeof GamesAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oxapay-webhook': {
      id: '/api/public/oxapay-webhook'
      path: '/api/public/oxapay-webhook'
      fullPath: '/api/public/oxapay-webhook'
      preLoaderRoute: typeof ApiPublicOxapayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cf-sdk': {
      id: '/api/public/cf-sdk'
      path: '/api/public/cf-sdk'
      fullPath: '/api/public/cf-sdk'
      preLoaderRoute: typeof ApiPublicCfSdkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cashfree-webhook': {
      id: '/api/public/cashfree-webhook'
      path: '/api/public/cashfree-webhook'
      fullPath: '/api/public/cashfree-webhook'
      preLoaderRoute: typeof ApiPublicCashfreeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ContactusRoute: ContactusRoute,
  HomeRoute: HomeRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundAndCancellationRoute: RefundAndCancellationRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  GamesAllRoute: GamesAllRoute,
  GamesPlaystationGamesRoute: GamesPlaystationGamesRoute,
  GamesSteamGamesRoute: GamesSteamGamesRoute,
  GamesSubscriptionsRoute: GamesSubscriptionsRoute,
  OrderIdRoute: OrderIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  GamesIndexRoute: GamesIndexRoute,
  ApiPublicCashfreeWebhookRoute: ApiPublicCashfreeWebhookRoute,
  ApiPublicCfSdkRoute: ApiPublicCfSdkRoute,
  ApiPublicOxapayWebhookRoute: ApiPublicOxapayWebhookRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
